name: lego
sha1: 00fe8d6f16a8381d25b12cd0b5a45d54fca6ad0e
entry: Init
rom:
  address: 0x08000000
  size: 8M
  segments:
    - name: crt0
      format: asm
      address: 0x000000
      size: 0x240
    - name: code_000300
      format: c
      address: 0x000300
      size: 0x8c
    - name: code_0003e0
      format: c
      address: 0x0003e0
      size: 0x7c
    - name: code_0004ac
      format: c
      address: 0x0004ac
      size: 0x3C4
    - name: code_0008b4
      format: c
      address: 0x0008b4
      size: 0x960
    - name: code_00122c
      format: c
      address: 0x00122c
      size: 0xbc
    - name: code_00132c
      format: c
      address: 0x00132c
      size: 0xf8
    - name: code_001454
      format: c
      address: 0x001454
      size: 0xb0
    - name: code_001534
      format: c
      address: 0x001534
      size: 0x1dc
    - name: code_001744
      format: c
      address: 0x001744
      size: 0x30
    - name: code_0017ac
      format: c
      address: 0x0017ac
      size: 0xc0
    - name: code_001894
      format: c
      address: 0x001894
      size: 0x1c8
    - name: code_001aa8
      format: c
      address: 0x001aa8
      size: 0x6f8
    - name: code_0021c0
      format: c
      address: 0x0021c0
      size: 0x7b4
    - name: code_0029c8
      format: c
      address: 0x0029c8
      size: 0x228
    - name: code_002c04
      format: c
      address: 0x002c04
      size: 0x11c
    - name: code_002d34
      format: c
      address: 0x002d34
      size: 0x7cc
    - name: code_00353c
      format: c
      address: 0x00353c
      size: 0x54
    - name: code_0035b4
      format: c
      address: 0x0035b4
      size: 0xd4
    - name: code_0036b0
      format: c
      address: 0x0036b0
      size: 0x168
    - name: code_0038c8
      format: c
      address: 0x0038c8
      size: 0xcd0
    - name: code_0045d8
      format: c
      address: 0x0045d8
      size: 0xc
    - name: code_0045f0
      format: c
      address: 0x0045f0
      size: 0x40
    - name: code_004670
      format: c
      address: 0x004670
      size: 0x18
    - name: code_004694
      format: c
      address: 0x004694
      size: 0x7c
    - name: code_00471c
      format: c
      address: 0x00471c
      size: 0x440
    - name: code_004b74
      format: c
      address: 0x004b74
      size: 0x1c
    - name: code_004bb0
      format: c
      address: 0x004bb0
      size: 0xfe4
    - name: code_005bbc
      format: c
      address: 0x005bbc
      size: 0x4c4
    - name: code_006180
      format: c
      address: 0x006180
      size: 0x380
    - name: code_006900
      format: c
      address: 0x006900
      size: 0x9b8
    - name: code_007354
      format: c
      address: 0x007354
      size: 0x9fc
    - name: code_007de0
      format: c
      address: 0x007de0
      size: 0x18cc
    - name: code_0096fc
      format: c
      address: 0x0096fc
      size: 0x24
    - name: code_009748
      format: c
      address: 0x009748
      size: 0x2ec0
    - name: code_00c608
      format: c
      address: 0x00c608
      size: 0x920
    - name: code_00cfcc
      format: c
      address: 0x00cfcc
      size: 0x1378
    - name: code_00e6e0
      format: c
      address: 0x00e6e0
      size: 0xe8
    - name: code_00e85c
      format: c
      address: 0x00e85c
      size: 0x4c4
    - name: code_00ed40
      format: c
      address: 0x00ed40
      size: 0xcf0
    - name: code_00fb04
      format: c
      address: 0x00fb04
      size: 0x8e0
    - name: code_010528
      format: c
      address: 0x010528
    - name: code_010a4c
      format: c
      address: 0x010a4c
    - name: code_0115a0
      format: c
      address: 0x0115a0
    - name: code_0117c4
      format: c
      address: 0x0117c4
    - name: code_012068
      format: c
      address: 0x012068
      size: 0x5118
    - name: code_0171fc
      format: c
      address: 0x0171fc
      size: 0x6fc
    - name: code_017920
      format: c
      address: 0x017920
      size: 0xa1c
    - name: code_018370
      format: c
      address: 0x018370
      size: 0x113c
    - name: code_01968c
      format: c
      address: 0x01968c
      size: 0x234
    - name: code_0199bc
      format: c
      address: 0x0199bc
      size: 0x128
    - name: code_019b38
      format: c
      address: 0x019b38
      size: 0xc9c
    - name: code_01b5d8
      format: c
      address: 0x01b5d8
      size: 0x3ff4
    - name: code_01f684
      format: c
      address: 0x01f684
      size: 0x24c8
    - name: code_021bb0
      format: c
      address: 0x021bb0
      size: 0x1cc4
    - name: code_023910
      format: c
      address: 0x023910
      size: 0x2c58
    - name: code_02699c
      format: c
      address: 0x02699c
      size: 0x7b8
    - name: code_027414
      format: c
      address: 0x027414
      size: 0xe8
    - name: code_0279a0
      format: c
      address: 0x0279a0
      size: 0x7098
    - name: code_02f850
      format: c
      address: 0x02f850
      size: 0x34d0
    - name: code_032d70
      format: c
      address: 0x032d70
      size: 0x42a4
    - name: code_037490
      format: c
      address: 0x037490
      size: 0x1090
    - name: code_038520
      format: c
      address: 0x038520
      size: 0x30a8
    - name: code_03b5c8
      format: c
      address: 0x03b5c8
      size: 0x834
    - name: code_03c010
      format: c
      address: 0x03c010
      size: 0x1bcc
    - name: code_03dbdc
      format: c
      address: 0x03dbdc
      size: 0x2c90
    - name: code_04086c
      format: c
      address: 0x04086c
    - name: code_042a3c
      format: asm
      address: 0x042a3c
      size: 0xa8c
    - name: _call_via_rX
      library: libgcc.a
      address: 0x0434c8
    - name: _divsi3
      library: libgcc.a
      address: 0x043504
    - name: _dvmd_tls
      library: libgcc.a
      address: 0x043598
    - name: _fixunssfsi
      library: libgcc.a
      address: 0x04359c
    - name: _modsi3
      library: libgcc.a
      address: 0x0435d0
    - name: _udivsi3
      library: libgcc.a
      address: 0x0436a0
    - name: _umodsi3
      library: libgcc.a
      address: 0x043718
    - name: dp-bit
      library: libgcc.a
      address: 0x0437d8
    - name: fp-bit
      library: libgcc.a
      address: 0x044574
    - name: _lshrdi3
      library: libgcc.a
      address: 0x044ec0
    - name: _muldi3
      library: libgcc.a
      address: 0x044ef4
    - name: _negdi2
      library: libgcc.a
      address: 0x044f64
    - name: memcpy
      library: libc.a
      address: 0x044f7c
    - name: memset
      library: libc.a
      address: 0x044fdc
    - name: qsort
      library: libc.a
      address: 0x045030
    - name: sprintf
      library: libc.a
      address: 0x0455c0
    - name: strchr
      library: libc.a
      address: 0x04563c
    - name: strcmp
      library: libc.a
      address: 0x0456c8
    - name: strcpy
      library: libc.a
      address: 0x045724
    - name: strlen
      library: libc.a
      address: 0x045770
    - name: strncpy
      library: libc.a
      address: 0x0457b4
    - name: vfprintf
      library: libc.a
      address: 0x045824
    - name: wsetup
      library: libc.a
      address: 0x046990
    - name: dtoa
      library: libc.a
      address: 0x046a3c
    - name: fflush
      library: libc.a
      address: 0x047890
    - name: findfp
      library: libc.a
      address: 0x047924
    - name: freer
      library: libc.a
      address: 0x047a80
    - name: fvwrite
      library: libc.a
      address: 0x047d00
    - name: fwalk
      library: libc.a
      address: 0x047f2c
    - name: locale
      library: libc.a
      address: 0x047f6c
    - name: makebuf
      library: libc.a
      address: 0x047fd8
    - name: mallocr
      library: libc.a
      address: 0x048210
    - name: mbtowc_r
      library: libc.a
      address: 0x0485d0
    - name: memchr
      library: libc.a
      address: 0x0485fc
    - name: memmove
      library: libc.a
      address: 0x04867c
    - name: mlock
      library: libc.a
      address: 0x048704
    - name: mprec
      library: libc.a
      address: 0x04870c
    - name: s_isinf
      library: libc.a
      address: 0x048fdc
    - name: s_isnan
      library: libc.a
      address: 0x049000
    - name: sbrkr
      library: libc.a
      address: 0x049020
    - name: stdio
      library: libc.a
      address: 0x04904c
      size: 0xc4
    - name: syscalls
      library: libc.a
      address: 0x049110
      size: 0x464
    - name: writer
      library: libc.a
      address: 0x049574
    - name: callocr
      library: libc.a
      address: 0x0495a4
    - name: closer
      library: libc.a
      address: 0x0495fc
    - name: errno
      library: libc.a
      address: 0x049628
    - name: fstatr
      library: libc.a
      address: 0x049634
    - name: libcfunc
      library: libc.a
      address: 0x049660
    - name: lseekr
      library: libc.a
      address: 0x049688
    - name: readr
      library: libc.a
      address: 0x0496b8
    - name: code_0496e8
      format: c
      address: 0x0496e8
    - name: code_0004ac
      format: c
      section: rodata
      address: 0x049700
      size: 0x5c
    - name: code_001aa8
      format: c
      section: rodata
      address: 0x04978c
      size: 0x4
    - name: vfprintf
      library: libc.a
      section: rodata
      address: 0x6cccc4
      size: 0x7a
    - name: dtoa
      library: libc.a
      section: rodata
      address: 0x6ccd40
    - name: impure
      library: libc.a
      section: rodata
      address: 0x6ccd54
    - name: locale
      library: libc.a
      section: rodata
      address: 0x6ccd58
    - name: mprec
      library: libc.a
      section: rodata
      address: 0x6ccd94
    - name: syscalls
      library: libc.a
      section: rodata
      address: 0x6cceb8
      size: 0x25
    - name: code_77ef7c
      format: c
      section: rodata
      address: 0x77ef7c
      size: 0x9a0
    - name: impure
      library: libc.a
      section: data
      address: 0x7d6268
    - name: locale
      library: libc.a
      section: data
      address: 0x7d6558
      size: 0x14
    - name: mallocr
      library: libc.a
      section: data
      address: 0x7d656c
      size: 0x444
ewram:
  address: 0x02000000
  size: 256K
  symbols:
    - name: dp-bit
      address: 0x0005b8
    - name: fp-bit
      address: 0x0005d0
    - name: syscalls
      address: 0x0005e0
build:
  files:
    ofiles:
      - src/*.o
      - asm/*.o
  constants:
    agbcc: /home/minirop/git/fireemblem8u/tools/agbcc
    as: $(DEVKITARM)/bin/arm-none-eabi-as
    cc1: $(AGBCC)/bin/old_agbcc
    cc1flags: -mthumb-interwork -Wimplicit -Wparentheses -O2 -fhex-asm
    asflags: -mcpu=arm7tdmi -mthumb-interwork -I include
    symbols: symbols.txt
    ldscript: ldscript.txt
    ld: $(DEVKITARM)/bin/arm-none-eabi-ld
    objcopy: $(DEVKITARM)/bin/arm-none-eabi-objcopy
  commands:
    - folder: asm
      extension: s
      exec:
        - $(AS) $(ASFLAGS) $(NAME).s -o $(NAME).o
    - folder: src
      extension: c
      exec:
        - $(CC1) $(CC1FLAGS) $(NAME).c -o $(NAME).s
        - $(AS) $(ASFLAGS) $(NAME).s -o $(NAME).o
    - $(LD) -T $(SYMBOLS) -T $(LDSCRIPT) -Map $(ROM).map $(OFILES) -L $(AGBCC)/lib -lc -lgcc -o $(ROM).elf
    - $(OBJCOPY) -O binary --pad-to 0x8000000 $(ROM).elf $(ROM).gba
